### ISSUE TITLE
pip install teyit

### ISSUE THREAD

**Issue by cleder** [isidentical/teyit#3]
Trying to install teyit from pypi:

```
pip install teyit 
ERROR: Could not find a version that satisfies the requirement teyit (from versions: none)
ERROR: No matching distribution found for teyit
```

**Comment by isidentical** [comment]
Teyit is only available for python3.9+. Could you confirm your python (`python -v`) version?

**Comment by cleder** [comment]
OK that explains it I tried on 3.8

**Comment by isidentical** [comment]
If i could find some time, i might port this to 3.7+ though pretty busy right now.

**Comment by cleder** [comment]
YAGNI, I would not invest time into that. I can confirm it works fine with python 3.9

**Comment by cleder** [comment]
I would mention it in the Readme though, just not to have to answer this question again.
I added teyit to https://github.com/cleder/awesome-python-testing

**Comment by isidentical** [comment]
Good idea, thanks!
